### ISSUE TITLE
Release 1.0.0-RC.3 checklist

### ISSUE THREAD

**Issue by AndrewEckart** [ssl-hep/ServiceX#202]
## Release 1.0.0-RC.3 checklist
* [x]  Merge PRs targeted for this milestone, and postpone any remaining issues/PRs to next milestone
* [x]  Update change log (#201)
* [x]  Create release branch in [ServiceX](https://github.com/ssl-hep/ServiceX) repo and freeze chart dependencies in `servicex/requirements.yaml`
* [x]  Create release branch in each service repo and freeze dependencies in `setup.py` or `requirements.txt`:
  * [x] [ServiceX_App](https://github.com/ssl-hep/ServiceX_App)
  * [x] [X509_Secrets](https://github.com/ssl-hep/X509_Secrets)
  * [x] [DID Finder](https://github.com/ssl-hep/ServiceX-DID-finder)
  * [x] [xAOD_CPP Transformer](https://github.com/ssl-hep/ServiceX_xAOD_CPP_transformer)
  * [x] [Uproot Transformer](https://github.com/ssl-hep/ServiceX_Uproot_Transformer)
  * [x] [xAOD Code Generator](https://github.com/ssl-hep/ServiceX_Code_Generator_FuncADL_xAOD)
  * [x] [Uproot Code Generator](https://github.com/ssl-hep/ServiceX_Code_Generator_FuncADL_uproot)
  * [x] [ConfigMap Code Generator](https://github.com/ssl-hep/ServiceX_Code_Generator_Config_File)
* [x]  Activate [ReadTheDocs version](https://readthedocs.org/projects/servicex/versions/) for the release branch
* [x]  Update links to docs in README on release branch
* [x]  Set chart version and app version in `servicex/Chart.yaml`
* [x]  Make sure that DockerHub has tags for this release in sslhep/servicex_app and other image repos
* [x]  Fix the default images and tags in `servicex/values.yaml` on release branch
* [x]  Publish new version of ServiceX chart to ssl-hep/servicex helm repo
* [x]  Make centrally-managed deployments to River cluster
* [x]  Ensure docs on release branch are pointing to the correct deployments
* [x]  Send announcement
