### ISSUE TITLE
Increase Scope of Integration Tests

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#481]
# Problem
We don't have an extensive integration test suite to validate new ServiceX deployments.

# Approach
1. Based on current tests in [ServiceX Backend-Tests](https://github.com/ssl-hep/servicex-backend-tests)
2. Add tests to exercise CERN Open Data DID Finder
3. Add test to exercise func_adl queries that will cause errors in both code generators
4. Add test to exercise errors in both transformers
5. Restore GHA run of tests
6. Configure [MeerCode dashboard](https://meercode.io/monitor)
7. Add slack notification of failures

# Tasks
- [x] Cleaned up the test and made the basics run again
- [x] Added tests to show transformer errors from missing fields in uproot and xAOD deployments
- [x] Added a test to show a code gen error in xAOD code gen
- [x] Added test to show code gen error for uproot
- [ ] Update Meercode dashboard
- [ ] Add slack notification of errors
