### ISSUE TITLE
PHYSLITE and R22

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#659]
# Story
_As a user/physicist I want to extract distributions from PHYSLITE so I can plot the data and otherwise us it in awkward array._

# Assumptions
1. Not willing to wait for PHYSLITE coffea/awkward behaviors - use the `EventLoop` and `AnalysisBase` interface
2. Use standard `func_adl` to access.
3. Use the <3.0 front end code (tho it should make no difference in the end).

# Acceptance Criteria
1. Extract data from a modern PHYSLITE `ttbar` sample and make a plot of jets in a demo Jupyter notebook.

# TODO:

* [ ] Update the code generator in ServiceX. MR submitted. Waiting for a merge
* [x] Automate the generation of the type packages for `fun_adl`. 
* [x] Generate a simple example

**Comment by gordonwatts** [comment]
None of the work should occur in this repo, as this is all front-end work. But this is left here to track this in the main SX project.

_Perhaps worth some discussion if this sort of thing should be appearing in a different repo, or attached to a different project._

**Comment by gordonwatts** [comment]
A blocker: we are using a very old version of `func-adl-xAOD` - we need to be up on version 2.1.1 (or 2.1 at least, rather than 2.0.1).

**Comment by gordonwatts** [comment]
After that xAOD is merged, then this should be fixed. A demo can be [found here](https://github.com/gordonwatts/func-adl-servicex-demos/blob/main/xAOD/04-jets-physlite.ipynb).

**Comment by gordonwatts** [comment]
And we now have [automated building of the packages you need to generate the types](https://github.com/iris-hep/func_adl_type_generator).

**Comment by ponyisi** [comment]
Is it at all possible to default people to the same naming convention as the uproot PHYSLITE schema is going to give us?

**Comment by gordonwatts** [comment]
The current schema is dictated by the EventLoop/AnalysisBase call schema. This is quite different from the uproot PHYSLITE behavior being developed by ATLAS. But, getting those two in  line is actually a great point. We should add a "coherence" task going forward in AMG.

That said, there is nothing wrong with developing aliases for things. The system currently supports that, other that you have to input the aliases you want, which is a bit painful.

**Comment by ponyisi** [comment]
We have the R22 transformer - is this done or does it need more?

**Comment by gordonwatts** [comment]
Yes - completed.
